### ISSUE TITLE
Upgrading from Plone 4.1.5 > 4.3.3 

### ISSUE THREAD

**Issue by mgrbyte** [collective/collective.dancing#11]
Hi,
We're looking at upgrading a plone site that uses singing and dancing,
and came across an issue whereby the buildout works but the instance crashes due to the following:

TypeError: ('object.**new**(Salt) is not safe, use persistent.Persistent.**new**()', <function _reconstructor at 0xb753d1b4>, (<class 'collective.dancing.channel.Salt'>, <type 'object'>, None))
2014-05-23 13:04:19 ERROR ZODB.Connection Couldn't load state for 0x1a78
Traceback (most recent call last):
  File "/home/zope/site/eggs/ZODB3-3.10.5-py2.6-linux-i686.egg/ZODB/Connection.py", line 860, in setstate
    self._setstate(obj)
  File "/home/zope/site/eggs/ZODB3-3.10.5-py2.6-linux-i686.egg/ZODB/Connection.py", line 914, in _setstate
    self._reader.setGhostState(obj, p)
  File "/home/zope/site/eggs/ZODB3-3.10.5-py2.6-linux-i686.egg/ZODB/serialize.py", line 612, in setGhostState
    state = self.getState(pickle)
  File "/home/zope/site/eggs/ZODB3-3.10.5-py2.6-linux-i686.egg/ZODB/serialize.py", line 605, in getState
    return unpickler.load()
  File "/home/dev/buildout.python/python-2.6/lib/python2.6/copy_reg.py", line 48, in _reconstructor
    obj = object.__new__(cls)
TypeError: ('object.**new**(Salt) is not safe, use Persistence.Persistent.**new**()', <function _reconstructor at 0xb753d1b4>, (<class 'collective.dancing.channel.Salt'>, <type 'object'>, None))

Can anyone recommend the best approach here?
I'm thinking i'll have to export the content whilst running under 4.1.5,
delete it from 4.3, then re-import?
Thanks!

**Comment by frisi** [comment]
this ticket is quite old. did you manage to fix the issue? would be great if you shared your experience with others.

when updating s&d I often had a `ComponentLookupError` for the `ISalt` which might be related, although your error looks quite different:

A [fix for this problem is documented in the s&d mailing list](http://groups.google.com/group/singing-dancing/browse_thread/thread/013e58fd02b1f84d/ec1bd94ba2fbe653):


Start the debug instance and use PDBDebugMode to access the portal object (http://nohost/plone/pdb)
and perform the following steps::
```python
    portal =  self.context.portal_url.getPortalObject()
    import collective.dancing
    collective.dancing.channel.tool_added(portal.portal_newsletters,None)
    import transaction
    transaction.commit()
```
